- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/Vpc_setup  # Ensure this file has the necessary variables or paths to your outputs

  tasks:
    - name: Import VPC Variables
      include_vars: vars/Vpc_setup

    - name: Delete S3 Bucket
      amazon.aws.s3_bucket:
        name: "{{ s3_bucket_name }}"
        state: absent

    - name: Delete NAT Gateway
      amazon.aws.ec2_vpc_nat_gateway:
        nat_gateway_id: "{{ NATGW_out.nat_gateway_id }}"
        region: "{{ region }}"
        state: absent
      ignore_errors: yes

    - name: Delete Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: absent
      ignore_errors: yes

    - name: Delete Public Subnet 1 in Zone1
      amazon.aws.ec2_vpc_subnet:
        subnet_id: "{{ pubsub1_out.subnet.id }}"
        region: "{{ region }}"
        state: absent
      ignore_errors: yes

    - name: Delete Public Subnet 2 in Zone2
      amazon.aws.ec2_vpc_subnet:
        subnet_id: "{{ pubsub2_out.subnet.id }}"
        region: "{{ region }}"
        state: absent
      ignore_errors: yes

    - name: Delete Public Subnet 3 in Zone3
      amazon.aws.ec2_vpc_subnet:
        subnet_id: "{{ pubsub3_out.subnet.id }}"
        region: "{{ region }}"
        state: absent
      ignore_errors: yes

    - name: Delete Private Subnet 1 in Zone1
      amazon.aws.ec2_vpc_subnet:
        subnet_id: "{{ privsub1_out.subnet.id }}"
        region: "{{ region }}"
        state: absent
      ignore_errors: yes

    - name: Delete Private Subnet 2 in Zone2
      amazon.aws.ec2_vpc_subnet:
        subnet_id: "{{ privsub2_out.subnet.id }}"
        region: "{{ region }}"
        state: absent
      ignore_errors: yes

    - name: Delete Private Subnet 3 in Zone3
      amazon.aws.ec2_vpc_subnet:
        subnet_id: "{{ privsub3_out.subnet.id }}"
        region: "{{ region }}"
        state: absent
      ignore_errors: yes

    - name: Delete Route Tables
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: absent
      ignore_errors: yes

    - name: Delete VPC
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: absent
      ignore_errors: yes
